OrdererOrgs:
  - Name: ordererorg1
    Domain: ordererorg1
    Specs:
      - Hostname: orderer1

PeerOrgs:
  - Name: peerorg1
    Domain: peerorg1
    Template:
      Count: 2
      Start: 1
    Users:
      Count: 1
#  - Name: peerorg2
#    Domain: peerorg2
#    Template:
#      Count: 2
#      Start: 1
#    Users:
#      Count: 1